<center class="mytitle">
**GT Numérique**
</center>

# Méthodes de Schwarz: quelques idées d'implémentation

<center>
<span>**Loic Gouarin**</span>
</center>
<center>
<span>12 décembre 2017</span>
</center>

### Plan

- Schwarz classique appliqué au problème de Poisson 1D
- Construction d'un préconditionneur "BDD" pour le problème d'élasticité linéaire 2D

## Schwarz classique pour le problème de Poisson 1D

### Problème étudié

On souhaite résoudre 

$$
\left\{
\begin{array}{l}
-\Delta u(x) = 1 \; \text{pour} \; x\in[0, 1], \\
u(0)= u(1) = 0.
\end{array}
\right.
$$

à l'aide d'un schéma aux différences finies.

### Initialisation du problème

In [1]:
import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as linsolve

In [2]:
N = 100
L = 1.
dx = 1./(N - 1)
x = np.arange(0, L+.5*dx, dx)

### Construction de la matrice et du second membre

In [3]:
A = sp.spdiags([-np.ones(N), 2*np.ones(N), -np.ones(N)],[-1, 0, 1], N, N).tocsc()
b = np.ones(N)*dx**2

On applique les conditions de bords

In [4]:
A[0 ,  0] = 1; A[ 0,  1] = 0
A[-1, -2] = 0; A[-1, -1] = 1

In [5]:
b[0] = 0; b[-1] = 0

### Résolution du système

In [6]:
LU = linsolve.factorized(A)

In [7]:
u = LU(b)

### Représentation de la solution

In [8]:
from bqplot import *
x_sc, y_sc = LinearScale(), LinearScale()

ax_x = Axis(label='x', scale=x_sc, grid_lines='solid')
ax_y = Axis(label='solution', scale=y_sc, orientation='vertical', grid_lines='solid')

In [9]:
line = Lines(x=x, y=u, scales={'x': x_sc, 'y': y_sc})

In [10]:
fig = Figure(axes=[ax_x, ax_y], marks=[line])
fig

Figure(axes=[Axis(label='x', scale=LinearScale(), side='bottom'), Axis(label='solution', orientation='vertical', scale=LinearScale(), side='left')], fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, layout=Layout(min_width='125px'), marks=[Lines(colors=['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf'], interactions={'hover': 'tooltip'}, scales={'x': LinearScale(), 'y': LinearScale()}, scales_metadata={'x': {'orientation': 'horizontal', 'dimension': 'x'}, 'y': {'orientation': 'vertical', 'dimension': 'y'}, 'color': {'dimension': 'color'}}, tooltip_style={'opacity': 0.9}, x=array([ 0.        ,  0.01010101,  0.02020202,  0.03030303,  0.04040404,
        0.05050505,  0.06060606,  0.07070707,  0.08080808,  0.09090909,
        0.1010101 ,  0.11111111,  0.12121212,  0.13131313,  0.14141414,
        0.15151515,  0.16161616,  0.17171717,  0.18181818,  0.19191919,
        0.2020202 ,  0.21212121,  0.22222222,  0.23232323,  0.24242424,
        0.25252525,  0.26262626,  0.27272727,  0.28282828,  0.29292929,
        0.3030303 ,  0.31313131,  0.32323232,  0.33333333,  0.34343434,
        0.35353535,  0.36363636,  0.37373737,  0.38383838,  0.39393939,
        0.4040404 ,  0.41414141,  0.42424242,  0.43434343,  0.44444444,
        0.45454545,  0.46464646,  0.47474747,  0.48484848,  0.49494949,
        0.50505051,  0.51515152,  0.52525253,  0.53535354,  0.54545455,
        0.55555556,  0.56565657,  0.57575758,  0.58585859,  0.5959596 ,
        0.60606061,  0.61616162,  0.62626263,  0.63636364,  0.64646465,
        0.65656566,  0.66666667,  0.67676768,  0.68686869,  0.6969697 ,
        0.70707071,  0.71717172,  0.72727273,  0.73737374,  0.74747475,
        0.75757576,  0.76767677,  0.77777778,  0.78787879,  0.7979798 ,
        0.80808081,  0.81818182,  0.82828283,  0.83838384,  0.84848485,
        0.85858586,  0.86868687,  0.87878788,  0.88888889,  0.8989899 ,
        0.90909091,  0.91919192,  0.92929293,  0.93939394,  0.94949495,
        0.95959596,  0.96969697,  0.97979798,  0.98989899,  1.        ]), y=array([ 0.        ,  0.00499949,  0.00989695,  0.01469238,  0.01938578,
        0.02397715,  0.02846648,  0.03285379,  0.03713907,  0.04132231,
        0.04540353,  0.04938272,  0.05325987,  0.057035  ,  0.06070809,
        0.06427916,  0.06774819,  0.07111519,  0.07438017,  0.07754311,
        0.08060402,  0.0835629 ,  0.08641975,  0.08917457,  0.09182736,
        0.09437812,  0.09682685,  0.09917355,  0.10141822,  0.10356086,
        0.10560147,  0.10754005,  0.10937659,  0.11111111,  0.1127436 ,
        0.11427405,  0.11570248,  0.11702887,  0.11825324,  0.11937557,
        0.12039588,  0.12131415,  0.12213039,  0.12284461,  0.12345679,
        0.12396694,  0.12437506,  0.12468115,  0.12488522,  0.12498725,
        0.12498725,  0.12488522,  0.12468115,  0.12437506,  0.12396694,
        0.12345679,  0.12284461,  0.12213039,  0.12131415,  0.12039588,
        0.11937557,  0.11825324,  0.11702887,  0.11570248,  0.11427405,
        0.1127436 ,  0.11111111,  0.10937659,  0.10754005,  0.10560147,
        0.10356086,  0.10141822,  0.09917355,  0.09682685,  0.09437812,
        0.09182736,  0.08917457,  0.08641975,  0.0835629 ,  0.08060402,
        0.07754311,  0.07438017,  0.07111519,  0.06774819,  0.06427916,
        0.06070809,  0.057035  ,  0.05325987,  0.04938272,  0.04540353,
        0.04132231,  0.03713907,  0.03285379,  0.02846648,  0.02397715,
        0.01938578,  0.01469238,  0.00989695,  0.00499949,  0.        ]))], scale_x=LinearScale(allow_padding=False, max=1.0, min=0.0), scale_y=LinearScale(allow_padding=False, max=1.0, min=0.0))

### Schwarz alterné (Schwarz 1870)

<center>
<img style="width:35%;" src="./figures/schwarz.png"/>
</center>

<table>
<tr>
<td>
$$
\scriptsize{
\left\{
\begin{array}{l}
\mathcal{L}(u_1^{k+1}) = f(x), \; x \in \Omega_1 \\
u_1^{k+1}(x) = g(x), \; x\in \partial \Omega_1 \bigcap \overline \Omega_1 \\
u_1^{k+1}(x) = u_2^k(x), \; x \in \Gamma_1
\end{array}
\right.}
$$
    </td>
<td>
$$
\scriptsize{
\left\{
\begin{array}{l}
\mathcal{L}(u_2^{k+1}) = f(x), \; x \in \Omega_2 \\
u_2^{k+1}(x) = g(x), \; x\in \partial \Omega_2 \bigcap \overline \Omega_2 \\
u_2^{k+1}(x) = u_1^{k+1}(x), \; x\in \Gamma_2
\end{array}
\right.
}
$$
    </td>
    </tr>
</table>

### Schwarz parallèle (Lions 1988)

<center>
<img style="width:35%;" src="./figures/schwarz.png"/>
</center>

<table>
<tr>
<td>
$$
\scriptsize{
\left\{
\begin{array}{l}
\mathcal{L}(u_1^{k+1}) = f(x), \; x \in \Omega_1 \\
u_1^{k+1}(x) = g(x), \; x\in \partial \Omega_1 \bigcap \overline \Omega_1 \\
u_1^{k+1}(x) = u_2^k(x), \; x \in \Gamma_1
\end{array}
\right.}
$$
    </td>
<td>
$$
\scriptsize{
\left\{
\begin{array}{l}
\mathcal{L}(u_2^{k+1}) = f(x), \; x \in \Omega_2 \\
u_2^{k+1}(x) = g(x), \; x\in \partial \Omega_2 \bigcap \overline \Omega_2 \\
u_2^{k+1}(x) = u_1^{k}(x), \; x\in \Gamma_2
\end{array}
\right.
}
$$
    </td>
    </tr>
</table>

### Utilisation du parallèlisme dans les notebooks

*Attention:* avant d'exécuter les lignes suivantes, il faut démarrer les processus en allant à la page qui se trouve sur la page de demarrage des notebooks dans l'onglet `IPython cluster`. Nous en démarrerons 4 pour la suite.

In [2]:
import ipyparallel as ipp
c = ipp.Client(profile='mpi')

In [3]:
view = c[:]
view.activate()
view.block = True

### mpi4py

`mpi4py` est une implémentation de MPI en Python.

MPI permet d'envoyer des messages entre processus.

Les types de message

- communications point à point
- communications collectives

### mpi4py

Nous aurons besoin dans la suite

- `COMM_WORLD`: communicateur englobant l'ensemble des processus initialisés.
- `size`: le nombre de processus
- `rank`: le numéro du processus
- `send` et `recv`: envoi et réception de valeurs

### Initialisation des processus

In [17]:
%%px
import mpi4py.MPI as mpi
import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as linsolve

size = mpi.COMM_WORLD.size
rank = mpi.COMM_WORLD.rank

N = 100
L = 1.
dx = 1./(N - 1)

### Découpage du domaine en sous domaines

In [18]:
%%px
Nl = (N-1)//size + 1
if mpi.COMM_WORLD.rank == size-1:
    Nl += N%size
    
Narray = mpi.COMM_WORLD.allgather(Nl-1)
tmp = np.cumsum(Narray)
tmp = np.insert(tmp, 0, 0)
tmp

Out[0:2]: array([ 0, 24, 48, 72, 96])

Out[1:2]: array([ 0, 24, 48, 72, 96])

Out[2:2]: array([ 0, 24, 48, 72, 96])

Out[3:2]: array([ 0, 24, 48, 72, 96])

### Découpage du domaine en sous domaines

In [19]:
%%px
beg = tmp[rank]*dx
end = tmp[rank+1]*dx

overlap = 2

if rank > 0:
    beg -= dx*overlap
if rank < size - 1:
    end += dx*overlap

xl = np.arange(beg, end + .5*dx, dx)

### Construction des matrices locales

In [20]:
%%px
n = xl.size

A = sp.spdiags([-np.ones(n), 2*np.ones(n), -np.ones(n)],[-1, 0, 1], n, n) # 1D poisson matrix
A = A.tocsr()

A[0 ,  0] = 1; A[ 0,  1] = 0;
A[-1, -2] = 0; A[-1, -1] = 1;

b = np.ones(n)*dx**2
b[0] = 0; b[-1] = 0

### Résolution des problèmes locaux

In [21]:
%%px 
LU = linsolve.factorized(A.tocsc())
u = LU(b)

### Algorithme de Schwarz parallèle

In [22]:
def update(nbite=100):
    U = []
    U.append(mpi.COMM_WORLD.allgather(u))
    X = mpi.COMM_WORLD.allgather(xl)
    for k in range(nbite):
        if rank == 0:
            mpi.COMM_WORLD.send(u[-1-2*overlap], rank + 1, rank)
            b[-1] = mpi.COMM_WORLD.recv(None, rank + 1, rank + 1)
        elif rank == size - 1:
            mpi.COMM_WORLD.send(u[2*overlap], rank - 1, rank)
            b[0] = mpi.COMM_WORLD.recv(None, rank - 1, rank - 1)
        else:
            mpi.COMM_WORLD.send(u[-1-2*overlap], rank + 1, rank)
            b[-1] = mpi.COMM_WORLD.recv(None, rank + 1, rank + 1)
            mpi.COMM_WORLD.send(u[2*overlap], rank - 1, rank)
            b[0] = mpi.COMM_WORLD.recv(None, rank - 1, rank - 1)
        u[:] = LU(b)
        U.append(mpi.COMM_WORLD.allgather(u))
    return X, U

In [4]:
from classical_schwarz import plot_solution
plot_solution(view)

interactive(children=(IntSlider(value=0, continuous_update=False, description='iteration'), Output()), _dom_classes=('widget-interact',))

interactive(children=(IntSlider(value=1, continuous_update=False, description='overlap', max=20, min=1), Output()), _dom_classes=('widget-interact',))

VBox(children=(HBox(children=(Play(value=0, description='Press play'), IntSlider(value=0, continuous_update=False, description='iteration'), IntSlider(value=1, continuous_update=False, description='overlap', max=20, min=1))), Figure(animation_duration=100, axes=[Axis(label='x', scale=LinearScale()), Axis(label='solution', orientation='vertical', scale=LinearScale())], fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, layout=Layout(min_width='125px'), marks=[Lines(colors=['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf'], interactions={'hover': 'tooltip'}, scales={'x': LinearScale(), 'y': LinearScale()}, scales_metadata={'x': {'orientation': 'horizontal', 'dimension': 'x'}, 'y': {'orientation': 'vertical', 'dimension': 'y'}, 'color': {'dimension': 'color'}}, tooltip_style={'opacity': 0.9}, x=array([ 0.        ,  0.01010101,  0.02020202,  0.03030303,  0.04040404,
        0.05050505,  0.06060606,  0.07070707,  0.08080808,  0.09090909,
        0.1010101 ,  0.11111111,  0.12121212,  0.13131313,  0.14141414,
        0.15151515,  0.16161616,  0.17171717,  0.18181818,  0.19191919,
        0.2020202 ,  0.21212121,  0.22222222,  0.23232323,  0.24242424,
        0.25252525]), y=array([ 0.        ,  0.00122436,  0.0023467 ,  0.003367  ,  0.00428528,
        0.00510152,  0.00581573,  0.00642792,  0.00693807,  0.00734619,
        0.00765228,  0.00785634,  0.00795837,  0.00795837,  0.00785634,
        0.00765228,  0.00734619,  0.00693807,  0.00642792,  0.00581573,
        0.00510152,  0.00428528,  0.003367  ,  0.0023467 ,  0.00122436,  0.        ])), Lines(colors=['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf'], interactions={'hover': 'tooltip'}, scales={'x': LinearScale(), 'y': LinearScale()}, scales_metadata={'x': {'orientation': 'horizontal', 'dimension': 'x'}, 'y': {'orientation': 'vertical', 'dimension': 'y'}, 'color': {'dimension': 'color'}}, tooltip_style={'opacity': 0.9}, x=array([ 0.23232323,  0.24242424,  0.25252525,  0.26262626,  0.27272727,
        0.28282828,  0.29292929,  0.3030303 ,  0.31313131,  0.32323232,
        0.33333333,  0.34343434,  0.35353535,  0.36363636,  0.37373737,
        0.38383838,  0.39393939,  0.4040404 ,  0.41414141,  0.42424242,
        0.43434343,  0.44444444,  0.45454545,  0.46464646,  0.47474747,
        0.48484848,  0.49494949]), y=array([ 0.        ,  0.00127538,  0.00244873,  0.00352005,  0.00448934,
        0.0053566 ,  0.00612182,  0.00678502,  0.00734619,  0.00780533,
        0.00816243,  0.00841751,  0.00857055,  0.00862157,  0.00857055,
        0.00841751,  0.00816243,  0.00780533,  0.00734619,  0.00678502,
        0.00612182,  0.0053566 ,  0.00448934,  0.00352005,  0.00244873,
        0.00127538,  0.        ])), Lines(colors=['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf'], interactions={'hover': 'tooltip'}, scales={'x': LinearScale(), 'y': LinearScale()}, scales_metadata={'x': {'orientation': 'horizontal', 'dimension': 'x'}, 'y': {'orientation': 'vertical', 'dimension': 'y'}, 'color': {'dimension': 'color'}}, tooltip_style={'opacity': 0.9}, x=array([ 0.47474747,  0.48484848,  0.49494949,  0.50505051,  0.51515152,
        0.52525253,  0.53535354,  0.54545455,  0.55555556,  0.56565657,
        0.57575758,  0.58585859,  0.5959596 ,  0.60606061,  0.61616162,
        0.62626263,  0.63636364,  0.64646465,  0.65656566,  0.66666667,
        0.67676768,  0.68686869,  0.6969697 ,  0.70707071,  0.71717172,
        0.72727273,  0.73737374]), y=array([ 0.        ,  0.00127538,  0.00244873,  0.00352005,  0.00448934,
        0.0053566 ,  0.00612182,  0.00678502,  0.00734619,  0.00780533,
        0.00816243,  0.00841751,  0.00857055,  0.00862157,  0.00857055,
        0.00841751,  0.00816243,  0.00780533,  0.00734619,  0.00678502,
        0.00612182,  0.0053566 ,  0.00448934,  0.00352005,  0.00244873,
        0.00127

## Problème d'élasticité linéaire 2D

### Description du problème

Nous considérons ici un corps élastique qui occupe, dans sa configuration de référence, un domaine borné $\Omega$ dans $\mathbb{R}^2$ avec un bord noté $\Gamma$.

Soit $\left\{ \Gamma_D, \Gamma_N\right\}$ une partition de $\Gamma$ où $\Gamma_N$ peut être vide.

Nous aurons

- des conditions de Dirichlet sur $\Gamma_D$,
- des conditions de Neumann sur $\Gamma_N$.

Soit $u=(u_1, u_2)$ le champs des déplacements de ce corps élastique.

### Description du problème

Sous l'hypothèse de petites déformations, les tenseurs de contraintes et de déformations s'écrivent

$$
\sigma_{ij}(u) = 2\mu\epsilon_{ij} + \lambda tr(\epsilon(u))\mathbb{1}_2, \; i,j=1,2,\\
$$
$$
\epsilon(u) = \frac{\nabla u+ \nabla u^T}{2},
$$

où $\lambda$ et $\mu$ sont les constantes de Lamé. Ces coefficients peuvent être calculés à partir du module d'Young $E$ et le coefficient de Poisson $\nu$

$$
\lambda = \frac{\nu E}{(1+\nu)(1-2\nu)}, \; \mu = \frac{E}{2(1+\nu)}.
$$

### Description du problème

En se donnant $f=\left(f_1, f_2\right)\in L^2(\Omega)$, $g=(g_1, g_2)\in L^2(\Gamma)$ et $u_D$, le problème étudié s'écrit

$$
\begin{array}{rll}
-div\sigma(u) &=& f, \; \text{dans} \; \Omega,\\
\sigma(u)\cdot n &=& g, \; \text{sur} \; \Gamma_N, \\
u &=& u_D,\; \text{sur} \; \Gamma_D. 
\end{array}
$$

### Description du problème

Soient

$$
\begin{array}{rll}
V &=& \left\{ v \in H^1(\Omega) \; : \; v=0 \; \text{sur} \; \Gamma_D \right\},\\
V^D &=& \left\{ v \in H^1(\Omega) \; : \; v=u_D \; \text{sur} \; \Gamma_D \right\}.
\end{array}
$$

### Description du problème
La formulation variationnelle du problème d'élasticité s'écrit

Trouver $u\in V^D$ tel que 

$$
\int_\Omega \epsilon(u):\mathbb{C}\epsilon(v)dx=\int_\Omega f\cdot v dx + \int_{\Gamma_N} g\cdot v ds, \; \forall v \in V.
$$

avec

$$
\mathbb{C}_{ijkl} = \lambda \delta_{ij}\delta_{kl} + \mu (\delta_{ik}\delta_{jl}+\delta_{il}\delta_{jk}), \; 1\leq i,j,k,l\leq 2,
$$

où $\delta_{ij}$ est le symbôle de Kronecker.

### Discrétisation éléments finis

Soit $\mathcal{Q}_h$ une quadrangulation de $\Omega$. Les espaces $V$ et $ V^D$ sont remplacés par leurs approximations discrètes $V_h$ et $V_h^D$ définies par

$$
\begin{array}{rll}
V_h &=& \left\{ v_h \in \mathcal{C}^0(\overline \Omega); \; v_{|T}\in \mathbb{Q}_1(Q), \; \forall Q\in \mathcal{Q_h}; \; v_{h|\Gamma_D}=0 \right\},\\
V_h^D &=& \left\{ v_h \in \mathcal{C}^0(\overline \Omega); \; v_{|T}\in \mathbb{Q}_1(Q), \; \forall Q\in \mathcal{Q_h}; \; v_{h|\Gamma_D}=u_D \right\}.
\end{array}
$$

### Discrétisation éléments finis
La formulation variationnelle discrète s'écrit

Trouver $u_h\in V_h^D$ tel que $\forall v_h \in V_h$

$$
\sum_{Q\in \mathcal{Q}_h}\int_Q \epsilon(u_h):\mathbb{C}\epsilon(v_h)dx=\sum_{Q\in \mathcal{Q}_h}\int_Q f\cdot v_h dx + \sum_{E\subset \Gamma_N}\int_{\Gamma_N} g\cdot v_h ds,
$$

avec $u_h=(u_{1h},u_{2h})\in V_h$,

$$
u_{\alpha h}=\sum \varphi_j(x) u_{\alpha}^{j}, \; \alpha = 1,2.
$$

### Assemblage de la matrice de rigidité

La matrice élémentaire s'écrit

$$
\displaystyle{A_{ij}^e = \int_Q \epsilon(\varphi_i): \mathbb{C}\epsilon(\varphi_j) dx}
$$

### Notation de Voigt

En remarquant que le tenseur $\mathbb{C}$ est symétrique et $\epsilon_{ij} = \epsilon_{ji}$, $\sigma(u_h) = \mathbb{C}\epsilon(u_h)$ peut se réécrire

$$
\left(
\begin{array}{c}
\sigma_{11} \\
\sigma_{22} \\
\sigma_{12} 
\end{array}
\right)
=
C \gamma(u_h),
$$

avec

$$
C = \left(
\begin{array}{ccc}
\lambda+2\mu & \lambda & 0 \\
\lambda & \lambda+2\mu & 0 \\
0 & 0 & \mu
\end{array}
\right)
\; \text{et} \;
\gamma(u) = \left(
\begin{array}{c}
\epsilon_{11} \\
\epsilon_{22} \\
2\epsilon_{12} 
\end{array}
\right)=
\left(
\begin{array}{c}
\frac{\partial u_1}{\partial x} \\
\frac{\partial u_2}{\partial y} \\ 
\frac{\partial u_1}{\partial y}+\frac{\partial u_2}{\partial x} 
\end{array}
\right)
$$

### Fonctions de base

<table>
<tr>
<td><img src="./figures/element.png"></img></td>
<td>
$$
\begin{array}{rll}
\varphi_1(x,y) &=& \displaystyle{\frac{(x-h_x)(y-h_y)}{h_xh_y}}\\
\varphi_2(x,y) &=& \displaystyle{-\frac{x(y-h_y)}{h_xh_y}}\\
\varphi_3(x,y) &=& \displaystyle{\frac{xy}{h_xh_y}}\\
\varphi_4(x,y) &=& \displaystyle{-\frac{(x-h_x)y}{h_xh_y}}
\end{array}
$$
    </td>
</tr>
</table>

Soit $u = (u_1, u_2, \cdots, u_8)$ les valeurs de la solution $u_h$ aux noeuds du quadrange $Q$. Alors

$$
\gamma(u) = \left(
\begin{array}{cccccccc}
\varphi_{1,x} & 0 & \varphi_{2,x} & 0 & \varphi_{3,x} & 0 & \varphi_{4,x} & 0 \\
0 & \varphi_{1,y} & 0 & \varphi_{2,y} & 0 & \varphi_{3,y} & 0 & \varphi_{4,y} \\
\varphi_{1,y} & \varphi_{1,x} &\varphi_{2,y} & \varphi_{2,x} &\varphi_{3,y} & \varphi_{3,x} &\varphi_{4,y} & \varphi_{4,x} 
\end{array}
\right)
\left(
\begin{array}{c}
u_1 \\
\vdots \\
u_8
\end{array}
\right)
= R u
$$

Il s'en suit

$$
\epsilon(v_h) : \mathbb{C}\epsilon(u_h) = v^tR^tCRu.
$$

La matrice élémentaire peut donc se réécrire comme

$$
A^e = R^tCR.
$$

### Utilisation de sympy

In [ ]:
import sympy as sp

lamb, mu = sp.symbols("lambda, mu")
dim = 2

C = sp.zeros(3, 3)
C[:dim, :dim] = lamb*sp.ones(dim, dim) + 2*mu*sp.eye(dim)
C[-1, -1] = mu

In [ ]:
sp.pprint(C)

### Définition des fonctions de base

In [ ]:
x, y, hx, hy = sp.symbols("x, y, hx, hy ")

basis_functions = [ (x - hx)*(y - hy)/(hx*hy),
                          -x*(y - hy)/(hx*hy),
                                  x*y/(hx*hy),
                          -(x - hx)*y/(hx*hy)]

sp.pprint(basis_functions)

### Construction de R

In [ ]:
phi = basis_functions
R = sp.zeros(C.shape[0], 2*len(phi))

deriv = [x, y]

for j in range(dim):
    for i in range(len(phi)):
        R[j, dim*i + j] = phi[i].diff(deriv[j])

for i in range(len(phi)):
    R[-1, dim*i] = phi[i].diff(y)
    R[-1, dim*i + 1] = phi[i].diff(x)

In [ ]:
sp.pprint(R)

### Construction de $A^e$

In [ ]:
A = R.T*C*R

Ae = sp.zeros(dim*len(phi), dim*len(phi))
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        Ae[i, j] = sp.integrate(A[i, j], (y, 0., hy), (x, 0., hx)).expand()
        Ae[i, j].together().factor()

In [ ]:
sp.pprint(Ae)

### PETSc (Portable, Extensible Toolkit for Scientific Computation)

<center>
<img style="width:70%;" src="./figures/petsc_1.png"/>
</center>

### PETSc (Portable, Extensible Toolkit for Scientific Computation)

**Langages supportés**

- C/C++
- Fortran
- Python (`petsc4py`)

**Interface avec des bibliothèques externes**

- FFTW
- Hyper
- MUMPS
- ParMetis,
- SuperLU,
- UMFPACK,
- ...

### DM

Petsc offre deux structures de données pour gérer les maillages

- `DMDA` pour les maillages uniformes cartésiens,
- `DMPlex` pour les maillages non structurés.

### DMDA

In [3]:
%%px
from petsc4py import PETSc

nx = ny = 5

da = PETSc.DMDA().create([nx, ny], dof=2, stencil_width=1)
da.setUniformCoordinates(xmax=1, ymax=1)

### DMDA (4 sous domaines)
<center>
<img style="width:60%" src="./figures/DMDA.png"/>
</center>

### Récupérer $x_s$, $gx_s$, $x_e$, $gx_e$, ...

In [4]:
%%px
print(PETSc.COMM_WORLD.rank, da.getRanges(), da.getGhostRanges())

[stdout:0] 2 ((0, 3), (3, 5)) ((0, 4), (2, 5))
[stdout:1] 0 ((0, 3), (0, 3)) ((0, 4), (0, 4))
[stdout:2] 1 ((3, 5), (0, 3)) ((2, 5), (0, 4))
[stdout:3] 3 ((3, 5), (3, 5)) ((2, 5), (2, 5))


### Parcourir les éléments avec une numérotation locale

In [5]:
%%px
da.getElements()

Out[0:3]: 
array([[ 0,  1,  5,  4],
       [ 1,  2,  6,  5],
       [ 4,  5,  9,  8],
       [ 5,  6, 10,  9]], dtype=int32)

Out[1:3]: 
array([[ 0,  1,  5,  4],
       [ 1,  2,  6,  5],
       [ 4,  5,  9,  8],
       [ 5,  6, 10,  9]], dtype=int32)

Out[2:3]: 
array([[0, 1, 4, 3],
       [1, 2, 5, 4],
       [3, 4, 7, 6],
       [4, 5, 8, 7]], dtype=int32)

Out[3:3]: 
array([[0, 1, 4, 3],
       [1, 2, 5, 4],
       [3, 4, 7, 6],
       [4, 5, 8, 7]], dtype=int32)

### Matrice et vecteur à partir d'un DMDA

In [6]:
%%px 
A = da.createMatrix()
x = da.createGlobalVec()
xlocal = da.createLocalVec()

On peut toujours accéder aux éléments en utilisant la numérotation globale.

In [7]:
%px x[0] = 1

In [11]:
%px print(da.getVecArray(x)[:])

[stdout:0] 
[[[ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]]]
[stdout:1] 
[[[ 1.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]]
[stdout:2] 
[[[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]]
[stdout:3] 
[[[ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]]]


### Assemblage de la matrice

In [17]:
%%px
from elasticity.assembling import getMatElemElasticity, getIndices

h, lamb, mu = [.25, .25], .25, .1

Melem = getMatElemElasticity(h, lamb, mu)
A = da.createMatrix()
elem = da.getElements()

dof = da.getDof()
for e in elem:
    ind = getIndices(e, dof)
    A.setValuesLocal(ind, ind, Melem, PETSc.InsertMode.ADD_VALUES)
A.assemble()

### Création du KSP

In [19]:
%%px
ksp = PETSc.KSP().create()
ksp.setOperators(A)
ksp.setType("cg")
pc = ksp.getPC()
pc.setType("gamg")
ksp.setFromOptions()

### Exemple

In [ ]:
import sys, petsc4py
petsc4py.init(sys.argv)
from petsc4py import PETSc
import numpy as np
from elasticity import *

def rhs(coords, rhs):
    rhs[..., 1] = -9.81

# set options
OptDB = PETSc.Options()
Lx = OptDB.getReal('Lx', 10)
Ly = OptDB.getReal('Ly', 1)
n  = OptDB.getInt('n', 16)
nx = OptDB.getInt('nx', Lx*n)
ny = OptDB.getInt('ny', Ly*n)

hx = Lx/(nx - 1)
hy = Ly/(ny - 1)

da = PETSc.DMDA().create([nx, ny], dof=2, stencil_width=1)
da.setUniformCoordinates(xmax=Lx, ymax=Ly)

# constant young modulus
E = 30000
# constant Poisson coefficient
nu = 0.4

lamb = (nu*E)/((1+nu)*(1-2*nu)) 
mu = .5*E/(1+nu)

x = da.createGlobalVec()
b = buildRHS(da, [hx, hy], rhs)
A = buildElasticityMatrix(da, [hx, hy], lamb, mu)
A.assemble()

bcApplyWest(da, A, b)

ksp = PETSc.KSP().create()
ksp.setOperators(A)
ksp.setFromOptions()

ksp.solve(b, x)

viewer = PETSc.Viewer().createVTK('solution_2d.vts', 'w', comm = PETSc.COMM_WORLD)
x.view(viewer)

In [66]:
! mpiexec -n 4 python demos/elasticity_2d.py -ksp_monitor -ksp_type cg -pc_type none

  0 KSP Residual norm 1.970318723957e+00 
  1 KSP Residual norm 1.432165904284e+01 
  2 KSP Residual norm 2.219869726949e+01 
  3 KSP Residual norm 2.764077139634e+01 
  4 KSP Residual norm 3.158233723647e+01 
  5 KSP Residual norm 3.427005962788e+01 
  6 KSP Residual norm 3.587643743803e+01 
  7 KSP Residual norm 3.695641381094e+01 
  8 KSP Residual norm 3.112716433941e+01 
  9 KSP Residual norm 3.233552704025e+01 
 10 KSP Residual norm 3.967300491207e+01 
 11 KSP Residual norm 3.793614594574e+01 
 12 KSP Residual norm 3.539435863206e+01 
 13 KSP Residual norm 4.270929800876e+01 
 14 KSP Residual norm 4.982073090505e+01 
 15 KSP Residual norm 4.378777106525e+01 
 16 KSP Residual norm 4.723107567670e+01 
 17 KSP Residual norm 3.582317931390e+01 
 18 KSP Residual norm 3.918278378786e+01 
 19 KSP Residual norm 3.891456267806e+01 
 20 KSP Residual norm 4.390818521013e+01 
 21 KSP Residual norm 4.199982907422e+01 
 22 KSP Residual norm 4.433964435802e+01 
 23 KSP Residual norm 5.2764858228

298 KSP Residual norm 6.537957459274e+01 
299 KSP Residual norm 6.762406598176e+01 
300 KSP Residual norm 6.353804777341e+01 
301 KSP Residual norm 6.222597428714e+01 
302 KSP Residual norm 6.355447333006e+01 
303 KSP Residual norm 6.498514985250e+01 
304 KSP Residual norm 6.499908869516e+01 
305 KSP Residual norm 6.414380580259e+01 
306 KSP Residual norm 6.932789134140e+01 
307 KSP Residual norm 6.760141802255e+01 
308 KSP Residual norm 6.374543743684e+01 
309 KSP Residual norm 6.226967141681e+01 
310 KSP Residual norm 6.093674491624e+01 
311 KSP Residual norm 6.609252175886e+01 
312 KSP Residual norm 6.728113134602e+01 
313 KSP Residual norm 6.776321437513e+01 
314 KSP Residual norm 6.791743142474e+01 
315 KSP Residual norm 6.322225202523e+01 
316 KSP Residual norm 6.414205944353e+01 
317 KSP Residual norm 6.721908806535e+01 
318 KSP Residual norm 6.175954118383e+01 
319 KSP Residual norm 6.273628362959e+01 
320 KSP Residual norm 6.500333570478e+01 
321 KSP Residual norm 6.5499832914

587 KSP Residual norm 3.050280115450e+01 
588 KSP Residual norm 2.871544525440e+01 
589 KSP Residual norm 2.581747622555e+01 
590 KSP Residual norm 2.403011881714e+01 
591 KSP Residual norm 2.340784931916e+01 
592 KSP Residual norm 2.209984032035e+01 
593 KSP Residual norm 2.008265210515e+01 
594 KSP Residual norm 1.862687097183e+01 
595 KSP Residual norm 1.766577278900e+01 
596 KSP Residual norm 1.633702542040e+01 
597 KSP Residual norm 1.518677187091e+01 
598 KSP Residual norm 1.411607875136e+01 
599 KSP Residual norm 1.294983268750e+01 
600 KSP Residual norm 1.211567401024e+01 
601 KSP Residual norm 1.157702811730e+01 
602 KSP Residual norm 1.052573725818e+01 
603 KSP Residual norm 9.128541216909e+00 
604 KSP Residual norm 8.404203046164e+00 
605 KSP Residual norm 7.754064808990e+00 
606 KSP Residual norm 7.034672574164e+00 
607 KSP Residual norm 7.165904872794e+00 
608 KSP Residual norm 6.354138925306e+00 
609 KSP Residual norm 5.858258955701e+00 
610 KSP Residual norm 5.4612146940

In [1]:
def plot_solution(filename):
    import vtk
    filename = 'solution_2d.vts'
    reader = vtk.vtkXMLStructuredGridReader()
    reader.SetFileName(filename)
    reader.Update()

    nodes_array = reader.GetOutput().GetPoints().GetData() 
    data_arrays = reader.GetOutput().GetPointData()
    u = data_arrays.GetArray(0)
    v = data_arrays.GetArray(1)
    
    from vtk.util.numpy_support import vtk_to_numpy
    import numpy as np
    nodes = vtk_to_numpy(nodes_array)
    u = vtk_to_numpy(u)
    v = vtk_to_numpy(v)
    
    x = nodes[:, 0] + u
    y = nodes[:, 1] + v
    
    from bqplot import pyplot as plt

    plt.figure()
    plt.scatter(x, y, color=np.sqrt(u**2 + v**2), default_size=2)
    plt.show()

In [2]:
plot_solution('solution_2d.vts')

VBox(children=(Figure(axes=[ColorAxis(scale=ColorScale()), Axis(scale=LinearScale()), Axis(orientation='vertical', scale=LinearScale())], fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, layout=Layout(min_width='125px'), marks=[Scatter(color=array([ 0.        ,  0.00850706,  0.01404378, ...,  4.04866468,
        4.08270167,  4.11673886]), colors=['DeepSkyBlue'], default_size=2, interactions={'hover': 'tooltip'}, scales={'color': ColorScale(), 'x': LinearScale(), 'y': LinearScale()}, scales_metadata={'x': {'orientation': 'horizontal', 'dimension': 'x'}, 'y': {'orientation': 'vertical', 'dimension': 'y'}, 'color': {'dimension': 'color'}, 'size': {'dimension': 'size'}, 'opacity': {'dimension': 'opacity'}, 'rotation': {'dimension': 'rotation'}, 'skew': {'dimension': 'skew'}}, tooltip_style={'opacity': 0.9}, x=array([  0.        ,   0.05772301,   0.11574732, ...,  10.14536629,
        10.20825917,  10.2711524 ]), y=array([ 0.        , -0.00675577, -0.00982087, ..., -3.03957449,
       -3.07368745, -3.10779931]))], scale_x=LinearScale(allow_padding=False, max=1.0, min=0.0), scale_y=LinearScale(allow_padding=False, max=1.0, min=0.0)), Toolbar(figure=Figure(axes=[ColorAxis(scale=ColorScale()), Axis(scale=LinearScale()), Axis(orientation='vertical', scale=LinearScale())], fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, layout=Layout(min_width='125px'), marks=[Scatter(color=array([ 0.        ,  0.00850706,  0.01404378, ...,  4.04866468,
        4.08270167,  4.11673886]), colors=['DeepSkyBlue'], default_size=2, interactions={'hover': 'tooltip'}, scales={'color': ColorScale(), 'x': LinearScale(), 'y': LinearScale()}, scales_metadata={'x': {'orientation': 'horizontal', 'dimension': 'x'}, 'y': {'orientation': 'vertical', 'dimension': 'y'}, 'color': {'dimension': 'color'}, 'size': {'dimension': 'size'}, 'opacity': {'dimension': 'opacity'}, 'rotation': {'dimension': 'rotation'}, 'skew': {'dimension': 'skew'}}, tooltip_style={'opacity': 0.9}, x=array([  0.        ,   0.05772301,   0.11574732, ...,  10.14536629,
        10.20825917,  10.2711524 ]), y=array([ 0.        , -0.00675577, -0.00982087, ..., -3.03957449,
       -3.07368745, -3.10779931]))], scale_x=LinearScale(allow_padding=False, max=1.0, min=0.0), scale_y=LinearScale(allow_padding=False, max=1.0, min=0.0)))))

### Construction d'un préconditionneur

On prend une partition sans recouvrement de $\Omega$.

$$
\left\{
\begin{array}{l}
\overline \Omega = \bigcup_{s=1}^N \overline \Omega_s \\
\Omega_s \cap \Omega_t = \emptyset; \; s \neq t,
\end{array}
\right.
$$

où $N$ est le nombre de sous domaines.

### Construction d'un préconditionneur

$$
M^{-1} = \sum_{s=1}^N R_s^TA_s^+R_s \; \text{où} \; A_s = D^{-1}_s A_{|\Omega_s} D^{-1}_s,
$$

où

$$
A_{|\Omega_s} = \int_{\Omega_s} \epsilon(v):\mathbb{C}\epsilon(u) dx \; + (BC \cap \Omega_s).
$$

$R_s$ est l'opérateur de restriction et $D_s$ une partition de l'unité de sorte que

$$
\sum_{s=1}^N R_s^TD_sR_s = I.
$$

### Projection A orthogonale sur $ker(Z^TA)$

On définit

$$
\Pi = I - Z(Z^TAZ)^{-1}Z^TA
$$

où $Z$ sont les vecteurs qui engendrent $\sum_{s=1}^N R_s^TKer(A_s)$.

Dans notre cas, $Ker(A_s) \subset D_s RBM$.

On a 

$$
\Pi^T A \Pi = A \Pi = \Pi^T A.
$$

### Construction de $R$ et de $D$

<center>
<img style="width:70%" src="./figures/partition.png"/>
</center>

### Construction de $R$ et de $D$

In [68]:
%%px
(xs, xe), (ys, ye) = da.getRanges()
(gxs, gxe), (gys, gye) = da.getGhostRanges()

Rlocal = da.createLocalVec()
Rlocal_a = da.getVecArray(Rlocal)
Rlocal_a[gxs:xe, gys:ye] = 1

# multiplicity
D = da.createGlobalVec()
Dlocal = da.createLocalVec()
da.localToGlobal(Rlocal, D, addv=PETSc.InsertMode.ADD_VALUES)
da.globalToLocal(D, Dlocal)

ERROR:root:Cell magic `%%px` not found.


### Construction de $\Pi$

In [ ]:
RBM = PETSc.NullSpace().createRigidBody(da.getCoordinates())
rbm_vecs = RBM.getVecs()

work1 = da.createLocalVec()
work2 = da.createLocalVec()

vecs= []
for i in range(mpi.COMM_WORLD.size):
    for ivec, rbm_vec in enumerate(rbm_vecs):
        vecs.append(da.createGlobalVec())
        work1.set(0)
        da.globalToLocal(rbm_vec, work2)
        if i == mpi.COMM_WORLD.rank:
            work1 = work2*Rlocal/Dlocal
        da.localToGlobal(work1, vecs[-1], addv=PETSc.InsertMode.ADD_VALUES)

# BC
Avecs = []
for vec in vecs:
    bcApplyWest_vec(da, vec)
    Avecs.append(A*vec)

# orthonormalize
for i, vec in enumerate(vecs):
    alphas = []
    for vec_ in Avecs[:i]:
        alphas.append(vec.dot(vec_))
    for alpha, vec_ in zip(alphas, vecs[:i]):
        vec.axpy(-alpha, vec_)
    vec.scale(1./np.sqrt(vec.dot(A*vec)))
    Avecs[i] = A*vec

### Construction du préconditionneur

In [69]:
class ASM(object):
    def __init__(self, da_global, D_global, vecs, Avecs, h, lamb, mu):
        self.da_global = da_global
        self.vecs = vecs
        self.Avecs = Avecs

        (xs, xe), (ys, ye) = self.da_global.getRanges()
        (gxs, gxe), (gys, gye) = self.da_global.getGhostRanges()
        self.block = (slice(gxs, xe), slice(gys, ye))

        self.da_local = PETSc.DMDA().create([xe-gxs, ye-gys], dof=2, 
                                            stencil_width=1,
                                            comm=PETSc.COMM_SELF)
        mx, my = self.da_local.getSizes()
        self.da_local.setUniformCoordinates(xmax=h[0]*mx, ymax=h[1]*my)

        A = buildElasticityMatrix(self.da_local, h, lamb, mu)
        A.assemble()

        D = self.da_local.createGlobalVec()
        Dlocal_a = self.da_local.getVecArray(D)
        Dlocal = self.da_global.createLocalVec()
        self.da_global.globalToLocal(D_global, Dlocal)
        D_a = self.da_global.getVecArray(Dlocal)

        Dlocal_a[:, :] = D_a[self.block]
        A.diagonalScale(D, D)

        if mpi.COMM_WORLD.rank == 0:
            bcApplyWestMat(self.da_local, A)

        self.nullspace = PETSc.NullSpace().createRigidBody(self.da_local.getCoordinates())
        u, v, r = self.nullspace.getVecs()
        u[:] /= D[:]
        v[:] /= D[:]
        r[:] /= D[:]
        if mpi.COMM_WORLD.rank == 0:
            bcApplyWest_vec(self.da_local, u)
            bcApplyWest_vec(self.da_local, v)
            bcApplyWest_vec(self.da_local, r)

        A.setNullSpace(self.nullspace)

        # build local solvers
        self.ksp = PETSc.KSP().create()
        self.ksp.setOperators(A)
        self.ksp.setOptionsPrefix("myasm_")
        self.ksp.setType('cg')
        pc = self.ksp.getPC()
        pc.setType('none')
        self.ksp.setFromOptions()

        # Construct work arrays
        self.work_global = self.da_global.createLocalVec()
        self.workg_global = self.da_global.createGlobalVec()
        self.work1_local = self.da_local.createGlobalVec()
        self.work2_local = self.da_local.createGlobalVec()

    def mult(self, mat, x, y):
        self.work_global.set(0.)
        self.da_global.globalToLocal(x, self.work_global)

        work_global_a = self.da_global.getVecArray(self.work_global)

        work1_local_a = self.da_local.getVecArray(self.work1_local)
        work1_local_a[:, :] = work_global_a[self.block]

        self.ksp.solve(self.work1_local, self.work2_local)

        self.work_global.set(0.)
        sol_a = self.da_local.getVecArray(self.work2_local)

        work_global_a[self.block] = sol_a[:, :]
        self.da_global.localToGlobal(self.work_global, y, addv=PETSc.InsertMode.ADD_VALUES)

        # Apply projection
        self.workg_global.set(0)
        for vec, Avec in zip(self.vecs, self.Avecs):
            self.workg_global += Avec.dot(y)*vec
        
        y -= self.workg_global
        
class PCASM(object):
    def setUp(self, pc):
        B, self.P = pc.getOperators()

    def apply(self, pc, x, y):
        y.array = self.P*x        

### Résolution du système avec notre nouveau préconditionneur

In [ ]:
def rhs(coords, rhs):
    rhs[..., 1] = -9.81

OptDB = PETSc.Options()
Lx = OptDB.getInt('Lx', 10)
Ly = OptDB.getInt('Ly', 1)
n  = OptDB.getInt('n', 16)
nx = OptDB.getInt('nx', Lx*n)
ny = OptDB.getInt('ny', Ly*n)

hx = Lx/(nx - 1)
hy = Ly/(ny - 1)

da = PETSc.DMDA().create([nx, ny], dof=2, stencil_width=1)
da.setUniformCoordinates(xmax=Lx, ymax=Ly)

# constant young modulus
E = 30000
# constant Poisson coefficient
nu = 0.4

lamb = (nu*E)/((1+nu)*(1-2*nu)) 
mu = .5*E/(1+nu)

x = da.createGlobalVec()
b = buildRHS(da, [hx, hy], rhs)
A = buildElasticityMatrix(da, [hx, hy], lamb, mu)
A.assemble()

bcApplyWest(da, A, b)

# build nullspace and multiplicity
D, vecs, Avecs = get_nullspace(da, A)

# set matrix of the preconditioner
asm = ASM(da, D, vecs, Avecs, [hx, hy], lamb, mu)
P = PETSc.Mat().createPython(
    [x.getSizes(), b.getSizes()], comm=da.comm)
P.setPythonContext(asm)
P.setUp()

# Set initial guess
ptilde = da.createGlobalVec()
for i in range(len(vecs)):
    ptilde += vecs[i].dot(b)*vecs[i]
x = ptilde
bcApplyWest_vec(da, x)

ksp = PETSc.KSP().create()
ksp.setOperators(A, P)
ksp.setOptionsPrefix("elas_")
ksp.setType("cg")
ksp.setInitialGuessNonzero(True)
# set our own preconditioner
pc = ksp.pc
pc.setType(pc.Type.PYTHON)
pc.setPythonContext(PCASM())
ksp.setFromOptions()

ksp.solve(b, x)

viewer = PETSc.Viewer().createVTK('solution_2d_bdd.vts', 'w', comm = PETSc.COMM_WORLD)
x.view(viewer)

In [71]:
! mpiexec -n 4 python demos/schwarz.py -elas_ksp_monitor

  Residual norms for elas_ solve.
  0 KSP Residual norm 1.029282029670e+02 
  1 KSP Residual norm 1.227135117725e-02 
  2 KSP Residual norm 1.118330669606e-03 
  3 KSP Residual norm 4.524011436624e-05 
  4 KSP Residual norm 1.351227085042e-05 


In [72]:
plot_solution('solution_2d_bdd.vts')

VBox(children=(Figure(axes=[ColorAxis(scale=ColorScale()), Axis(scale=LinearScale()), Axis(orientation='vertical', scale=LinearScale())], fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, layout=Layout(min_width='125px'), marks=[Scatter(color=array([ 0.        ,  0.00850706,  0.01404378, ...,  4.04866468,
        4.08270167,  4.11673886]), colors=['DeepSkyBlue'], default_size=2, interactions={'hover': 'tooltip'}, scales={'color': ColorScale(), 'x': LinearScale(), 'y': LinearScale()}, scales_metadata={'x': {'orientation': 'horizontal', 'dimension': 'x'}, 'y': {'orientation': 'vertical', 'dimension': 'y'}, 'color': {'dimension': 'color'}, 'size': {'dimension': 'size'}, 'opacity': {'dimension': 'opacity'}, 'rotation': {'dimension': 'rotation'}, 'skew': {'dimension': 'skew'}}, tooltip_style={'opacity': 0.9}, x=array([  0.        ,   0.05772301,   0.11574732, ...,  10.14536629,
        10.20825917,  10.2711524 ]), y=array([ 0.        , -0.00675577, -0.00982087, ..., -3.03957449,
       -3.07368745, -3.10779931]))], scale_x=LinearScale(allow_padding=False, max=1.0, min=0.0), scale_y=LinearScale(allow_padding=False, max=1.0, min=0.0)), Toolbar(figure=Figure(axes=[ColorAxis(scale=ColorScale()), Axis(scale=LinearScale()), Axis(orientation='vertical', scale=LinearScale())], fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, layout=Layout(min_width='125px'), marks=[Scatter(color=array([ 0.        ,  0.00850706,  0.01404378, ...,  4.04866468,
        4.08270167,  4.11673886]), colors=['DeepSkyBlue'], default_size=2, interactions={'hover': 'tooltip'}, scales={'color': ColorScale(), 'x': LinearScale(), 'y': LinearScale()}, scales_metadata={'x': {'orientation': 'horizontal', 'dimension': 'x'}, 'y': {'orientation': 'vertical', 'dimension': 'y'}, 'color': {'dimension': 'color'}, 'size': {'dimension': 'size'}, 'opacity': {'dimension': 'opacity'}, 'rotation': {'dimension': 'rotation'}, 'skew': {'dimension': 'skew'}}, tooltip_style={'opacity': 0.9}, x=array([  0.        ,   0.05772301,   0.11574732, ...,  10.14536629,
        10.20825917,  10.2711524 ]), y=array([ 0.        , -0.00675577, -0.00982087, ..., -3.03957449,
       -3.07368745, -3.10779931]))], scale_x=LinearScale(allow_padding=False, max=1.0, min=0.0), scale_y=LinearScale(allow_padding=False, max=1.0, min=0.0)))))